name = "path-kv"
main = "example.ts"
compatibility_date = "2025-04-29"
dev.port = 3000

routes = [
  { pattern = "pathkv.wilmake.com", custom_domain = true }
]

[[kv_namespaces]]
binding = "PATH_KV"
id = "b3bc7e280b8a45e3bd1475bb5a4f1414"